@BASE_URL = http://localhost:5000
###
GET {{BASE_URL}}/api/users
###
GET {{BASE_URL}}
###
POST {{BASE_URL}}/api/users
Content-Type: application/json

{     "username":"cccd",
    "email":"dil1@hotmail.com",
    "password":"111"
}

###

POST {{BASE_URL}}/api/users/login
Content-Type: application/json

{
    "email":"dilancil1@hotmail.com",
    "password":"111"

}
###
DELETE {{BASE_URL}}/api/users/62406189f78ae1e4984651a
###
PATCH {{BASE_URL}}/api/users/62534dea134052b8d4b6ea2c
Content-Type: application/json

{

    "password":"19935",
    "name":"aysen",
    "surname":"deniz"
}
###
GET {{BASE_URL}}/api/users/624b1639e0c25b5186f77c0e

###
POST {{BASE_URL}}/api/dietitians
Content-Type: application/json

{    "username":"kerimn@hotmail.com",
    "email":"kerimn@hotmail.com",
    "password":"1451"
}

###

POST {{BASE_URL}}/api/dietitians/login
Content-Type: application/json

{
     "email":"kerim@hotmail.com",
    "password":"111"
}
###
GET {{BASE_URL}}/api/foods/yumurta
###
GET {{BASE_URL}}/api/users/6252da6e1e7176d9131c3efe
###

POST {{BASE_URL}}/api/foods
Content-Type: application/json

{
    "name":"yumurta",
    "quantity":"1 adet",
    "calorie":"6"
}
###

PATCH {{BASE_URL}}/api/dietLists/myList
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjU1YzYzN2I3NWI0ZTkxMjhmN2JlMWQiLCJpYXQiOjE2NDk3OTMyMjIsImV4cCI6MTY0OTc5NjgyMn0.GZ1C_05G2eJbsVjt1XC-TcDDEEdm3JIO-K9j4HlD0K8


{

    "Monday_breakfast":"eggy",
    "dietitian":"6255cc22fda5e8744188b700"

}

###

GET {{BASE_URL}}/api/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjU1YzYzN2I3NWI0ZTkxMjhmN2JlMWQiLCJpYXQiOjE2NTA4MjIzMDksImV4cCI6MTY1MDgyNTkwOX0.Yjovp35pBFNJBHSbSf61lNy9_yZiuAqbD-RSGAwCNhU

###
GET {{BASE_URL}}/api/dietLists/myList
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjU1YzYzN2I3NWI0ZTkxMjhmN2JlMWQiLCJpYXQiOjE2NDk3ODg0ODMsImV4cCI6MTY0OTc5MjA4M30.9D__n16NipfZhi_xTrGWr4vTeNmIE_V3Ob9t-FU-Isc

###

GET {{BASE_URL}}/api/dietitians/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjU1Y2MyMmZkYTVlODc0NDE4OGI3MDAiLCJlbWFpbCI6ImtlcmltQGhvdG1haWwuY29tIiwiaWF0IjoxNjUwNTc2ODMxLCJleHAiOjE2NTA1ODA0MzF9.SWZRGQzcV2du0TKiOmPjWCjtMU2XhBryDjpbqkHvnMw

###
PATCH {{BASE_URL}}/api/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjU1YzYzN2I3NWI0ZTkxMjhmN2JlMWQiLCJpYXQiOjE2NDk3OTc2MDAsImV4cCI6MTY0OTgwMTIwMH0.yRUH8ZeGgJv5H3isOaX5CUPLAIgZir0bI4f_Z4bYQSs

{
    
    "dietitian":"6255cc22fda5e8744188b700"

}


###

GET {{BASE_URL}}/api/users/myUsers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjU1Y2MyMmZkYTVlODc0NDE4OGI3MDAiLCJlbWFpbCI6ImtlcmltQGhvdG1haWwuY29tIiwiaWF0IjoxNjQ5Nzk4MjMyLCJleHAiOjE2NDk4MDE4MzJ9.9_DLr9nZy8R7OoQZAEY-38LHrA4TTy-Zd9kF76wCXi4

###

POST {{BASE_URL}}/api/weights
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjU1YzYzN2I3NWI0ZTkxMjhmN2JlMWQiLCJpYXQiOjE2NTA2Mzc2NzcsImV4cCI6MTY1MDY0MTI3N30.hHjsTwfhrDA9p4vn_v40s05cfeO5ZqYcd1kHwe0Pvl4

{
    "weight":"630"
}
###
GET {{BASE_URL}}/api/weights
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjU1YzYzN2I3NWI0ZTkxMjhmN2JlMWQiLCJpYXQiOjE2NTA1NjYxNjMsImV4cCI6MTY1MDU2OTc2M30.DY4l5I_rxIp4LHY21NlQfO9VFRyWuUVCGmPmarTIDqI

###