@BASE_URL = http://localhost:5000
###
GET {{BASE_URL}}/api/dietitians/elkfif/getdietitian

###
GET {{BASE_URL}}/api/dietitians/myUsers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjY2ZDIyMDk3N2M5ZjA1NzI5NzQ2NGYiLCJlbWFpbCI6ImtlcmlmZ21tbW5AaG90bWFpbC5jb20iLCJpYXQiOjE2NTE2NzU1MDEsImV4cCI6MTY1MTY5MzUwMX0.HvwUGVZDVsAEtwyo5HxhbO4EJpXhJ5lnerZo2khjfQU

###
PATCH {{BASE_URL}}/api/dietLists/eee/requestDietList
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjY2Y2Q0NGE2NzYzOWZhODM3MGRlODYiLCJpYXQiOjE2NTE2NzQ1MjEsImV4cCI6MTY1MTY5MjUyMX0.acM62he5OpTMXKda45dXJADC_oU-M_xkWetfre9TL8g
###
GET {{BASE_URL}}
###
POST {{BASE_URL}}/api/users
Content-Type: application/json

{     "username":"elkfif",
    "email":"delkfif@hotmail.com",
    "password":"111"
}

###

POST {{BASE_URL}}/api/users/login
Content-Type: application/json

{
    "email":"delif@hotmail.com",
    "password":"111"

}
###
DELETE {{BASE_URL}}/api/users/62406189f78ae1e4984651a
###
PATCH {{BASE_URL}}/api/users/62534dea134052b8d4b6ea2c
Content-Type: application/json

{

    "password":"19935",
    "name":"aysen",
    "surname":"deniz"
}
###
GET {{BASE_URL}}/api/users/624b1639e0c25b5186f77c0e

###
POST {{BASE_URL}}/api/dietitians
Content-Type: application/json

{   "username": "eee",
    "email":"kerifgmmmn@hotmail.com",
    "password":"1451"
}

###

POST {{BASE_URL}}/api/dietitians/login
Content-Type: application/json

{
     "email":"kerifgmmmn@hotmail.com",
    "password":"1451"
}
###
GET {{BASE_URL}}/api/foods/yumurta
###
GET {{BASE_URL}}/api/users/6252da6e1e7176d9131c3efe
###

POST {{BASE_URL}}/api/foods
Content-Type: application/json

{
    "name":"yumurta",
    "quantity":"1 adet",
    "calorie":"6"
}
###

PATCH {{BASE_URL}}/api/dietLists/elkfif/writeDietList
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjY2ZDIyMDk3N2M5ZjA1NzI5NzQ2NGYiLCJlbWFpbCI6ImtlcmlmZ21tbW5AaG90bWFpbC5jb20iLCJpYXQiOjE2NTE2NjU0NTIsImV4cCI6MTY1MTY4MzQ1Mn0.jvCgPVfypgEURnFCtakePQRjrNHGpc8-unaoYkmO1Us


{

    "breakfast":"eggy"

}

###

GET {{BASE_URL}}/api/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjY2Y2Q0NGE2NzYzOWZhODM3MGRlODYiLCJpYXQiOjE2NTE2ODg1MjYsImV4cCI6MTY1MTcwNjUyNn0.WaCwUZZSlmKrgUrNtK3R6UfcqNHD3OmMZVCdJDEOII0

###
GET {{BASE_URL}}/api/dietLists/myList
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjU1YzYzN2I3NWI0ZTkxMjhmN2JlMWQiLCJpYXQiOjE2NDk3ODg0ODMsImV4cCI6MTY0OTc5MjA4M30.9D__n16NipfZhi_xTrGWr4vTeNmIE_V3Ob9t-FU-Isc

###

GET {{BASE_URL}}/api/dietitians/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjY2ZDIyMDk3N2M5ZjA1NzI5NzQ2NGYiLCJlbWFpbCI6ImtlcmlmZ21tbW5AaG90bWFpbC5jb20iLCJpYXQiOjE2NTEzNDgwMDcsImV4cCI6MTY1MTM2NjAwN30.SZAhjNn3YNT8kuzxSdTaMHqyZYIbuLR0Vwrnr3YU-gE



###
PATCH {{BASE_URL}}/api/dietitians/me
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjY2ZDIyMDk3N2M5ZjA1NzI5NzQ2NGYiLCJlbWFpbCI6ImtlcmlmZ21tbW5AaG90bWFpbC5jb20iLCJpYXQiOjE2NTEzNDgwMDcsImV4cCI6MTY1MTM2NjAwN30.SZAhjNn3YNT8kuzxSdTaMHqyZYIbuLR0Vwrnr3YU-gE

{
    
    "name":"6255huc",
    "surname":"hjj",
    "birthday": "2021-11-11"
}

###
PATCH {{BASE_URL}}/api/users/me
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjY2Y2Q0NGE2NzYzOWZhODM3MGRlODYiLCJpYXQiOjE2NTEwMTUzMTcsImV4cCI6MTY1MTAzMzMxN30.OPDD-KyQ5gMNPLeVq1F5Q8NdyPO63b77mUkJisCdQd8
{
    
    "name":"6255hc"

}


###

GET {{BASE_URL}}/api/users/myUsers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjY2Y2Q0NGE2NzYzOWZhODM3MGRlODYiLCJpYXQiOjE2NTA5MDQ2MTYsImV4cCI6MTY1MDkwODIxNn0.4pmHz8kxOqNWsaOApvIoKfnjJNPHNs820DLrMK6r71o

###

POST {{BASE_URL}}/api/weights
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjY2Y2Q0NGE2NzYzOWZhODM3MGRlODYiLCJpYXQiOjE2NTE4MjY1NDEsImV4cCI6MTY1MTg0NDU0MX0.PplDa8H-cFRsBACZYdlgaKWH2CZgx7TgpZoQsnX8SIU

{    "date":"2022-03-01",
     "weight":"70"
}
###
GET {{BASE_URL}}/api/weights
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjY2Y2Q0NGE2NzYzOWZhODM3MGRlODYiLCJpYXQiOjE2NTE4MjY1NDEsImV4cCI6MTY1MTg0NDU0MX0.PplDa8H-cFRsBACZYdlgaKWH2CZgx7TgpZoQsnX8SIU

###